--------------------------------------------------------
--  Constraints for Table CLUSTERES
--------------------------------------------------------


  ALTER TABLE  "CLUSTERES" MODIFY ("REGIONALID" NOT NULL ENABLE);
  ALTER TABLE  "CLUSTERES" MODIFY ("CLUSTERNAME" NOT NULL ENABLE);
  ALTER TABLE  "CLUSTERES" ADD PRIMARY KEY ("CLUSTERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------


  ALTER TABLE  "USERS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE  "USERS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE  "USERS" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE  "USERS" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE  "USERS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CENTRALS
--------------------------------------------------------


  ALTER TABLE  "CENTRALS" MODIFY ("CENTRALNAME" NOT NULL ENABLE);
  ALTER TABLE  "CENTRALS" ADD PRIMARY KEY ("CENTRALID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACCOUNTS
--------------------------------------------------------


  ALTER TABLE  "ACCOUNTS" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE  "ACCOUNTS" MODIFY ("BRANCHID" NOT NULL ENABLE);
  ALTER TABLE  "ACCOUNTS" MODIFY ("ACCOUNTNUMBER" NOT NULL ENABLE);
  ALTER TABLE  "ACCOUNTS" MODIFY ("ACCOUNTOPENINGDATE" NOT NULL ENABLE);
  ALTER TABLE  "ACCOUNTS" MODIFY ("ACCOUNTTYPE" NOT NULL ENABLE);
  ALTER TABLE  "ACCOUNTS" MODIFY ("ACCOUNTTYPE2" NOT NULL ENABLE);
  ALTER TABLE  "ACCOUNTS" ADD PRIMARY KEY ("ACCOUNTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADDITIONALDETAILS
--------------------------------------------------------


  ALTER TABLE  "ADDITIONALDETAILS" MODIFY ("ACCOUNTID" NOT NULL ENABLE);
  ALTER TABLE  "ADDITIONALDETAILS" MODIFY ("KYC_STAUS" NOT NULL ENABLE);
  ALTER TABLE  "ADDITIONALDETAILS" MODIFY ("ISMOBILEBANKINGACTIVE" NOT NULL ENABLE);
  ALTER TABLE  "ADDITIONALDETAILS" MODIFY ("ISINTERNETBANKINGACTIVE" NOT NULL ENABLE);
  ALTER TABLE  "ADDITIONALDETAILS" MODIFY ("ISCUSTOMERUSENEFTORRTGS" NOT NULL ENABLE);
  ALTER TABLE  "ADDITIONALDETAILS" MODIFY ("ISEMAILATIVATE" NOT NULL ENABLE);
  ALTER TABLE  "ADDITIONALDETAILS" MODIFY ("ISDEBITCARDACTIVATE" NOT NULL ENABLE);
  ALTER TABLE  "ADDITIONALDETAILS" MODIFY ("TOTALPOINT" NOT NULL ENABLE);
  ALTER TABLE  "ADDITIONALDETAILS" ADD PRIMARY KEY ("ADDITIONALDETAILSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICES
--------------------------------------------------------


  ALTER TABLE  "SERVICES" MODIFY ("SERVICENAME" NOT NULL ENABLE);
  ALTER TABLE  "SERVICES" ADD PRIMARY KEY ("SERVICEID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PASSWORD_RESETS
--------------------------------------------------------

  ALTER TABLE  "PASSWORD_RESETS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE  "PASSWORD_RESETS" MODIFY ("TOKEN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CALL_SUMMARY
--------------------------------------------------------


  ALTER TABLE  "CALL_SUMMARY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ZONALS
--------------------------------------------------------


  ALTER TABLE  "ZONALS" MODIFY ("CENTRALID" NOT NULL ENABLE);
  ALTER TABLE  "ZONALS" MODIFY ("ZONENAME" NOT NULL ENABLE);
  ALTER TABLE  "ZONALS" ADD PRIMARY KEY ("ZONALID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PRODUCTS
--------------------------------------------------------


  ALTER TABLE  "PRODUCTS" ADD PRIMARY KEY ("PRODUCTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;

--------------------------------------------------------
--  Constraints for Table REGIONALS
--------------------------------------------------------

  ALTER TABLE  "REGIONALS" MODIFY ("ZONALID" NOT NULL ENABLE);
  ALTER TABLE  "REGIONALS" MODIFY ("REGIONALNAME" NOT NULL ENABLE);
  ALTER TABLE  "REGIONALS" ADD PRIMARY KEY ("REGIONALID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BRANCHES
--------------------------------------------------------

  ALTER TABLE  "BRANCHES" MODIFY ("CLUSTERID" NOT NULL ENABLE);
  ALTER TABLE  "BRANCHES" MODIFY ("BRANCHNAME" NOT NULL ENABLE);
  ALTER TABLE  "BRANCHES" ADD PRIMARY KEY ("BRANCHID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------


  ALTER TABLE  "CUSTOMERS" MODIFY ("CUSTOMERNAME" NOT NULL ENABLE);
  ALTER TABLE  "CUSTOMERS" MODIFY ("MOBILENO" NOT NULL ENABLE);
  ALTER TABLE  "CUSTOMERS" MODIFY ("CUSTOMERPROFESSION" NOT NULL ENABLE);
  ALTER TABLE  "CUSTOMERS" MODIFY ("CUSTOMERADDRESS" NOT NULL ENABLE);
  ALTER TABLE  "CUSTOMERS" MODIFY ("CREATEDBY" NOT NULL ENABLE);
  ALTER TABLE  "CUSTOMERS" MODIFY ("CREATED_AT" NOT NULL ENABLE);
  ALTER TABLE  "CUSTOMERS" ADD PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PASSWORD_RESET_TOKENS
--------------------------------------------------------

  ALTER TABLE  "PASSWORD_RESET_TOKENS" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE  "PASSWORD_RESET_TOKENS" MODIFY ("TOKEN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRANSACTIONHISTORY
--------------------------------------------------------


  ALTER TABLE  "TRANSACTIONHISTORY" MODIFY ("ACCOUNTID" NOT NULL ENABLE);
  ALTER TABLE  "TRANSACTIONHISTORY" MODIFY ("CURRENTBALANCE" NOT NULL ENABLE);
  ALTER TABLE  "TRANSACTIONHISTORY" MODIFY ("CURRENTDATE" NOT NULL ENABLE);
  ALTER TABLE  "TRANSACTIONHISTORY" MODIFY ("BALANCEGROWTHPERCENT" NOT NULL ENABLE);
  ALTER TABLE  "TRANSACTIONHISTORY" MODIFY ("NOOFTRANSACTIONINLAST30DAY" NOT NULL ENABLE);
  ALTER TABLE  "TRANSACTIONHISTORY" MODIFY ("DAYSINCELASTCONTACT" NOT NULL ENABLE);
  ALTER TABLE  "TRANSACTIONHISTORY" MODIFY ("NEXTCONTACTEDDATE" NOT NULL ENABLE);
  ALTER TABLE  "TRANSACTIONHISTORY" ADD PRIMARY KEY ("TRANSACTIONHISTORYID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LEADPRODUCTDETAILS
--------------------------------------------------------

  ALTER TABLE  "LEADPRODUCTDETAILS" MODIFY ("LEADID" NOT NULL ENABLE);
  ALTER TABLE  "LEADPRODUCTDETAILS" ADD PRIMARY KEY ("LEADPRODUCTDETAILSID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LEADS
--------------------------------------------------------
 alter table leads add constraint fk_Accounts_Leads foreign key(accountid)references Accounts(accountid);
  ALTER TABLE  "LEADS" MODIFY ("ACCOUNTID" NOT NULL ENABLE);
  ALTER TABLE  "LEADS" MODIFY ("CROID" NOT NULL ENABLE);
  ALTER TABLE  "LEADS" MODIFY ("CONTACTEDDATE" NOT NULL ENABLE);
  ALTER TABLE  "LEADS" MODIFY ("LEADTIME" NOT NULL ENABLE);
  ALTER TABLE  "LEADS" MODIFY ("NEXTCONTACTDATE" NOT NULL ENABLE);
  ALTER TABLE  "LEADS" ADD PRIMARY KEY ("LEADID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PERSONAL_ACCESS_TOKENS
--------------------------------------------------------

  ALTER TABLE  "PERSONAL_ACCESS_TOKENS" MODIFY ("TOKENABLE_TYPE" NOT NULL ENABLE);
  ALTER TABLE  "PERSONAL_ACCESS_TOKENS" MODIFY ("TOKENABLE_ID" NOT NULL ENABLE);
  ALTER TABLE  "PERSONAL_ACCESS_TOKENS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE  "PERSONAL_ACCESS_TOKENS" MODIFY ("TOKEN" NOT NULL ENABLE);
  ALTER TABLE  "PERSONAL_ACCESS_TOKENS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ROLES
--------------------------------------------------------

  ALTER TABLE  "ROLES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE  "ROLES" MODIFY ("GUARD_NAME" NOT NULL ENABLE);
  ALTER TABLE  "ROLES" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE  "ACCOUNTS" ADD CONSTRAINT "FK_ACCOUNTS_CUSTOMERS" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES  "CUSTOMERS" ("CUSTOMERID") ENABLE;
  ALTER TABLE  "ACCOUNTS" ADD CONSTRAINT "FK_ACCOUNTS_BRANCHES" FOREIGN KEY ("BRANCHID")
	  REFERENCES  "BRANCHES" ("BRANCHID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ADDITIONALDETAILS
--------------------------------------------------------

  ALTER TABLE  "ADDITIONALDETAILS" ADD CONSTRAINT "FK_ADDITIONALDETAILS_ACCOUNTS" FOREIGN KEY ("ACCOUNTID")
	  REFERENCES  "ACCOUNTS" ("ACCOUNTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BRANCHES
--------------------------------------------------------

  ALTER TABLE  "BRANCHES" ADD CONSTRAINT "FK_BRANCHES_CLUSTERES" FOREIGN KEY ("CLUSTERID")
	  REFERENCES  "CLUSTERES" ("CLUSTERID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLUSTERES
--------------------------------------------------------

  ALTER TABLE  "CLUSTERES" ADD CONSTRAINT "FK_CLUSTERES_REGIONALS" FOREIGN KEY ("REGIONALID")
	  REFERENCES  "REGIONALS" ("REGIONALID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CRO_DTLS
--------------------------------------------------------

  ALTER TABLE  "CRO_DTLS" ADD CONSTRAINT "FK_CRO_DTLS" FOREIGN KEY ("CRO_ID")
	  REFERENCES  "USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LEADPRODUCTDETAILS
--------------------------------------------------------

  ALTER TABLE  "LEADPRODUCTDETAILS" ADD CONSTRAINT "FK_LEADPRODUCTDETAILS_PRODUCTS" FOREIGN KEY ("PRODUCTID")
	  REFERENCES  "PRODUCTS" ("PRODUCTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LEADS
--------------------------------------------------------

  ALTER TABLE  "LEADS" ADD CONSTRAINT "FK_LEADS_SERVICES" FOREIGN KEY ("SERVICEID")
	  REFERENCES  "SERVICES" ("SERVICEID") ENABLE;
  ALTER TABLE  "LEADS" ADD CONSTRAINT "FK_LEADS_PRODUCTS" FOREIGN KEY ("PRODUCTID")
	  REFERENCES  "PRODUCTS" ("PRODUCTID") ENABLE;
  ALTER TABLE  "LEADS" ADD CONSTRAINT "FK_LEADS_CROID" FOREIGN KEY ("CROID")
	  REFERENCES  "USERS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REGIONALS
--------------------------------------------------------

  ALTER TABLE  "REGIONALS" ADD CONSTRAINT "FK_REGIONALS_ZONALS" FOREIGN KEY ("ZONALID")
	  REFERENCES  "ZONALS" ("ZONALID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTIONHISTORY
--------------------------------------------------------

  ALTER TABLE  "TRANSACTIONHISTORY" ADD CONSTRAINT "FK_TRANSACTIONHISTORY_ACCOUNTS" FOREIGN KEY ("ACCOUNTID")
	  REFERENCES  "ACCOUNTS" ("ACCOUNTID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ZONALS
--------------------------------------------------------

  ALTER TABLE  "ZONALS" ADD CONSTRAINT "FK_ZONALS_CENTRAL" FOREIGN KEY ("CENTRALID")
	  REFERENCES  "CENTRALS" ("CENTRALID") ENABLE;