
--=================================================================================================================================================
--=================================================================================================================================================
--TABLE CREATION QUERIES

--=================================================================================================================================================
--=================================================================================================================================================

--------------------------------------------------------
--  DDL for Table ACCOUNTS
--------------------------------------------------------

  CREATE TABLE  ACCOUNTS  
   (	 ACCOUNTID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 CUSTOMERID  NUMBER, 
	 BRANCHID  NUMBER, 
	 ACCOUNTNUMBER  NUMBER, 
	 ACCOUNTOPENINGDATE  TIMESTAMP (6) DEFAULT SYSDATE, 
	 ACCOUNTTYPE  VARCHAR2(10 BYTE), 
	 ACCOUNTTYPE2  VARCHAR2(100 BYTE)
   );
--------------------------------------------------------
--  DDL for Table ADDITIONALDETAILS
--------------------------------------------------------

  CREATE TABLE  ADDITIONALDETAILS  
   (	 ADDITIONALDETAILSID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 ACCOUNTID  NUMBER, 
	 KYC_STAUS  VARCHAR2(10 BYTE), 
	 ISMOBILEBANKINGACTIVE  VARCHAR2(10 BYTE), 
	 ISINTERNETBANKINGACTIVE  VARCHAR2(10 BYTE), 
	 ISCUSTOMERUSENEFTORRTGS  VARCHAR2(10 BYTE), 
	 ISEMAILATIVATE  VARCHAR2(10 BYTE), 
	 ISDEBITCARDACTIVATE  VARCHAR2(10 BYTE), 
	 TOTALPOINT  NUMBER, 
	 CREATED_AT  TIMESTAMP (6) DEFAULT SYSDATE, 
	 UPDATED_AT  TIMESTAMP (6) DEFAULT NULL, 
	 DID_CUSTOMER_SELF_TRANSFER_TO_OTHER_BANKS_IN_LAST_90_DAYS  VARCHAR2(10 BYTE), 
	 TRANSACTIONS_IN_LAST_30_DAYS  NUMBER, 
	 DAYS_SINCE_LAST_TRANSACTION_ON_MOBILE_BANKING  NUMBER, 
	 DAYS_SINCE_LAST_TRANSACTION_ON_INTERNET_BANKING  NUMBER, 
	 HAS_CUSTOMER_USED_DEBIT_CARD_IN_LAST_30_DAYS  VARCHAR2(10 BYTE), 
	 PRODUCTS_CROSS_SOLD_TO_CUSTOMERS  VARCHAR2(250 BYTE), 
	 HIGHEST_TRANSACTION_IN_THISMONTH  NUMBER
   );
--------------------------------------------------------
--  DDL for Table BRANCHES
--------------------------------------------------------

  CREATE TABLE  BRANCHES  
   (	 BRANCHID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 CLUSTERID  NUMBER, 
	 BRANCHNAME  VARCHAR2(50 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table CALL_SUMMARY
--------------------------------------------------------

  CREATE TABLE  CALL_SUMMARY  
   (	 ID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 ACCOUNTID  NUMBER, 
	 CROID  NUMBER, 
	 CONTACTED_TIME  VARCHAR2(5 BYTE), 
	 CONTACT_CHANNEL  NUMBER, 
	 CUSTOMER_STATUS  NUMBER, 
	 PRODUCT_ID  VARCHAR2(256 BYTE) DEFAULT null, 
	 SERVICE_ID  NUMBER DEFAULT null, 
	 CONVERSATION_SUMMARY  CLOB DEFAULT null, 
	 NEXT_CALLBACK_DATE  TIMESTAMP (6), 
	 CREATED_AT  TIMESTAMP (6) DEFAULT null, 
	 UPDATED_AT  TIMESTAMP (6) DEFAULT null
   ) ;
--------------------------------------------------------
--  DDL for Table CENTRALS
--------------------------------------------------------

  CREATE TABLE  CENTRALS  
   (	 CENTRALID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 CENTRALNAME  VARCHAR2(50 BYTE)
   ) ;
--------------------------------------------------------
--  DDL for Table CLUSTERES
--------------------------------------------------------

  CREATE TABLE  CLUSTERES  
   (	 CLUSTERID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 REGIONALID  NUMBER, 
	 CLUSTERNAME  VARCHAR2(100 BYTE)
   );
--------------------------------------------------------
--  DDL for Table CRO_DTLS
--------------------------------------------------------

  CREATE TABLE  CRO_DTLS  
   (	 ID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 CRO_ID  NUMBER, 
	 TARGET_BALANCE  NUMBER DEFAULT NULL, 
	 SA_TARGET_BALANCE  NUMBER DEFAULT NULL, 
	 CA_TARGET_BALANCE  NUMBER DEFAULT NULL, 
	 MIN_DATE  DATE
   );
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE  CUSTOMERS  
   (	 CUSTOMERID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 CUSTOMERNAME  VARCHAR2(100 BYTE), 
	 MOBILENO  NUMBER, 
	 CUSTOMERPROFESSION  VARCHAR2(50 BYTE), 
	 CUSTOMERADDRESS  VARCHAR2(500 BYTE), 
	 CREATEDBY  NUMBER, 
	 CREATED_AT  TIMESTAMP (6) DEFAULT SYSDATE, 
	 UPDATEDBY  NUMBER DEFAULT NULL, 
	 UPDATED_AT  DATE DEFAULT NULL, 
	 CUSTID  NUMBER DEFAULT null, 
	 CUST_STATUS  VARCHAR2(256 BYTE)
   );
--------------------------------------------------------
--  DDL for Table LEADPRODUCTDETAILS
--------------------------------------------------------

  CREATE TABLE  LEADPRODUCTDETAILS  
   (	 LEADPRODUCTDETAILSID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 LEADID  NUMBER, 
	 PRODUCTID  NUMBER DEFAULT NULL
   );
--------------------------------------------------------
--  DDL for Table LEADS
--------------------------------------------------------

  CREATE TABLE  LEADS  
   (	 LEADID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 ACCOUNTID  NUMBER, 
	 CROID  NUMBER, 
	 CONTACTEDDATE  TIMESTAMP (6) DEFAULT SYSDATE, 
	 LEADTIME  VARCHAR2(5 BYTE), 
	 SERVICEID  NUMBER DEFAULT NULL, 
	 NEXTCONTACTDATE  TIMESTAMP (6), 
	 LASTCONTACTCHANNEL  VARCHAR2(200 BYTE), 
	 STATUS  VARCHAR2(200 BYTE), 
	 CONVERSATION_SUMMERY  CLOB, 
	 PRODUCTID  NUMBER, 
	 STSTUS  VARCHAR2(200 BYTE), 
	 LEADSTAGE  NUMBER(10,0), 
	 TATDELAY  NUMBER(10,2), 
	 CONVERTEDDATE  TIMESTAMP (6), 
	 ESTIMATEDDATE  TIMESTAMP (6), 
	 REASON_FOR_DELAY  VARCHAR2(255 BYTE) DEFAULT null, 
	 PRIORITY  NUMBER(3,2), 
	 SLUG  VARCHAR2(256 BYTE), 
	 ISLEAD  NUMBER DEFAULT 0
   );
--------------------------------------------------------
--  DDL for Table LIFECYCLECRO
--------------------------------------------------------

  CREATE TABLE  LIFECYCLECRO  
   (	 LIFECYCLE_ID  NUMBER DEFAULT null, 
	 CRO_ID  NUMBER DEFAULT null
   );
--------------------------------------------------------
--  DDL for Table PASSWORD_RESETS
--------------------------------------------------------

  CREATE TABLE  PASSWORD_RESETS  
   (	 EMAIL  VARCHAR2(255 BYTE), 
	 TOKEN  VARCHAR2(255 BYTE), 
	 CREATED_AT  TIMESTAMP (6) DEFAULT NULL
   );
--------------------------------------------------------
--  DDL for Table PASSWORD_RESET_TOKENS
--------------------------------------------------------

  CREATE TABLE  PASSWORD_RESET_TOKENS  
   (	 EMAIL  VARCHAR2(255 BYTE), 
	 TOKEN  VARCHAR2(255 BYTE), 
	 CREATED_AT  TIMESTAMP (6) DEFAULT NULL
   );
--------------------------------------------------------
--  DDL for Table PERSONAL_ACCESS_TOKENS
--------------------------------------------------------

  CREATE TABLE  PERSONAL_ACCESS_TOKENS  
   (	 ID  NUMBER(20,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 TOKENABLE_TYPE  VARCHAR2(255 BYTE), 
	 TOKENABLE_ID  NUMBER, 
	 NAME  VARCHAR2(255 BYTE), 
	 TOKEN  VARCHAR2(64 BYTE), 
	 ABILITIES  VARCHAR2(3000 BYTE) DEFAULT NULL, 
	 LAST_USED_AT  TIMESTAMP (6) DEFAULT NULL, 
	 EXPIRES_AT  TIMESTAMP (6) DEFAULT NULL, 
	 CREATED_AT  TIMESTAMP (6) DEFAULT NULL, 
	 UPDATED_AT  TIMESTAMP (6) DEFAULT NULL
   ) ;
--------------------------------------------------------
--  DDL for Table PRODUCTS
--------------------------------------------------------

  CREATE TABLE  PRODUCTS  
   (	 PRODUCTID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 PRODUCTNAME  VARCHAR2(50 BYTE), 
	 USUALTATDAYS  NUMBER, 
	 PRODUCT_ORDER  NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Table REGIONALS
--------------------------------------------------------

  CREATE TABLE  REGIONALS  
   (	 REGIONALID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 ZONALID  NUMBER, 
	 REGIONALNAME  VARCHAR2(50 BYTE)
   );
--------------------------------------------------------
--  DDL for Table ROLES
--------------------------------------------------------

  CREATE TABLE  ROLES  
   (	 ID  NUMBER(20,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 NAME  VARCHAR2(255 BYTE), 
	 GUARD_NAME  VARCHAR2(255 BYTE), 
	 CREATED_AT  TIMESTAMP (6) DEFAULT NULL, 
	 UPDATED_AT  TIMESTAMP (6) DEFAULT NULL
   );
--------------------------------------------------------
--  DDL for Table SERVICES
--------------------------------------------------------

  CREATE TABLE  SERVICES  
   (	 SERVICEID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 SERVICENAME  VARCHAR2(50 BYTE), 
	 USUALTATDAYS  NUMBER
   );
--------------------------------------------------------
--  DDL for Table TEMP_TABLE
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE  TEMP_TABLE  
   (	 ID  NUMBER
   ) ON COMMIT DELETE ROWS ;
--------------------------------------------------------
--  DDL for Table TRANSACTIONHISTORY
--------------------------------------------------------

  CREATE TABLE  TRANSACTIONHISTORY  
   (	 TRANSACTIONHISTORYID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 ACCOUNTID  NUMBER, 
	 CURRENTBALANCE  NUMBER(20,2), 
	 CURRENTDATE  DATE DEFAULT sysdate, 
	 BALANCEGROWTHPERCENT  NUMBER(6,2), 
	 NOOFTRANSACTIONINLAST30DAY  NUMBER, 
	 DAYSINCELASTCONTACT  NUMBER, 
	 NEXTCONTACTEDDATE  TIMESTAMP (6), 
	 AMB  NUMBER(10,2), 
	 AMB_IN_LAST_MONTH  NUMBER(10,2), 
	 AMB_IN_T_3_MONTH  NUMBER(10,2), 
	 DAYS_SINCE_LAST_CREDIT_TRANSACTION  NUMBER
   ) ;
--------------------------------------------------------
--  DDL for Table USERDETAILS
--------------------------------------------------------

  CREATE TABLE  USERDETAILS  
   (	 USERID  NUMBER, 
	 TYPEID  NUMBER, 
	 TYPENAME  VARCHAR2(255 BYTE)
   );
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE  USERS  
   (	 ID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 NAME  VARCHAR2(255 BYTE), 
	 EMAIL  VARCHAR2(255 BYTE), 
	 ROLE_ID  NUMBER, 
	 EMAIL_VERIFIED_AT  TIMESTAMP (6) DEFAULT NULL, 
	 PASSWORD  VARCHAR2(255 BYTE), 
	 REMEMBER_TOKEN  VARCHAR2(100 BYTE) DEFAULT NULL, 
	 CREATED_AT  TIMESTAMP (6) DEFAULT NULL, 
	 UPDATED_AT  TIMESTAMP (6) DEFAULT NULL, 
	 PARENTID  NUMBER DEFAULT null
   )  ;
--------------------------------------------------------
--  DDL for Table ZONALS
--------------------------------------------------------

  CREATE TABLE  ZONALS  
   (	 ZONALID  NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	 CENTRALID  NUMBER, 
	 ZONENAME  VARCHAR2(50 BYTE)
   );
